baseURL: http://business-science.io/
languageCode: en-us
title: Data Science for Business
theme: "hugo-fresh-data-science"
# Put in your google analytics tracking code without quotes like this: UA-XXXXXX...
googleAnalytics: # UA-XXXXX...

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Put your formspree URL in like this:  https://formspree.io/f/...
  formspreeURL: "YOUR FORMSPREE URL"
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/icon-logo.png
    link: /
    brandName: Profitable Business with Data Science
    # Default width/height. Uncomment if you need to change
    width: 40
    height: 40
  
  # Web Fonts Available Here: https://fonts.google.com/
  googleFontImport: 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@400;600&family=Montserrat:wght@700&family=Roboto+Condensed&family=Abhaya+Libre:wght@400;600$&family=Lato&display=swap'
  header_font: "Montserrat"
  body_font: "Roboto"
  
  # css
  css:
    secondary_color: "#2251ff" # "#F39200" "#4FC1EA" "#00efb7" (Controls Buttons, Accents)
    mutedgrey_color: "#999" # "#999" # Contols writing 
    greydark_color: "#4a4a4a" # "#4a4a4a" Controls Headers
    bluegrey_color: "#000" # "#444F60", #2c3e50 (Controls Headers & Footer Background)
    navbar_color: "#FFF" # white: "#FFF", gray: #2c3e50
    navbar_text_color: "#000" # grey: #999, dark-grey: #444, black: #000
  
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbarStyle:
  navbar:
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  - title: Consulting
    url: /consulting
  # - title: Testimonials
  #   url: /testimonials
  # - title: Blog
  #   url: /blog
  - title: Applications
    url: /applications
  - title: Contact Us
    url: /contact
  - title: Apply Now
    url: /applynow
    button: true
  
  applynow:
    title: Claim your free consultation right now.
    subtitle: Let's have a conversation today 
    # googleFormEmbed: "https://docs.google.com/forms/d/e/1FAIpQLSeaux5ms6OjbAzMM1C6tyYBA9nqveniqk_WEdmQLK3uOHSQ9Q/viewform?embedded=true"
    googleFormEmbed: "https://forms.office.com/Pages/ResponsePage.aspx?id=UTnvpgGjtUu3LIRIjntLoiL4QkbvbIlPiY5INqTE8n1UMjEzTEhSRkdKTFdYU1VVVVhTNjgwRldKNC4u&embed=true"
  
  contact:
    title: Contact Us
    subtitle: What can we help you with?
    buttontext: Contact Us
  
  section1_attention:
    # Main hero title
    # title: "Save $2M with better forecasting in 120 days"
    title: "Increase net income (EBIT) by 40% in 120 days"
    titleTextColor: "white"
    # Hero subtitle (optional)
    subtitle: "We help struggling European retailers attract new customers and increase customer value"
    heroBackgroundColor: "#000000c7"
    
    # Button text
    buttontext: "How it works"
    # Where the main hero button links to
    buttonlink: "/#section2"
    # Hero image (from static/images/___)
    # Can get these images from flaticon.com
    image: illustrations/mockups/nostradamus_app.jpg
    backgroundImage: illustrations/pexels-pixabay-373543.jpg
    # USE DS SOLUTION OPTIONS BEFORE GENERATING CLIENTS - FORECASTING, SKU, PRICING ETC.
    # clientstext: "Some of the clients we've helped:"
    # # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek.svg
    # - tribe.svg
    # - kromo.svg
    # - infinite.svg
    # - gutwork.svg
 
  section2_transformation:
    title: "How Data Science AI works" 
    subtitle: "Increase sales and reduce costs through tailored data science solutions for pricing, personalized promotions, forecasting, store-specific SKU selection, employee turnover and many more!"
    # icons are located in static > images > illustrations > icons
    tile_size: is-one-quarter
    tile_height: "400px"
    tiles:
    - title: "Step 1"
      subtitle: Speak With A Consultant Today
      icon: conversation.svg
      text: Speak with one of our business consultants about your need and how our tailored solutions can help you.
    - title: "Step 2"
      subtitle: Unveal Hidden Business Opportunities
      icon: forecasting.svg
      text: We work with your team to discover opportunities for growth and cost reduction, backed up with data.
    - title: "Step 3"
      subtitle: Use Tailored Data Driven Solutions
      icon: collaboration.svg
      text: We design the right solutions to solve your most buring problem and train your team to use it.
    - title: "Step 4"
      subtitle: Monitor Savings
      icon: monitoring.svg
      text: We help your team measure improvements versus baselines. We make sure you get your EBIT increase by 120 days.
  
  section3_interest:
    title: Get fast results
    subtitle: With our already built applications for forecasting and employee turnover prediction.
    image: illustrations/mockups/nostradamus_app.jpg
    tile_size: is-one-third
    tile_height: "200px"
    tiles:
    - title: "Results in 120 days"
      subtitle: "Go from losing money to saving money without hiring multiple consultants or handling time-consuming deployments yourself."
    - title: "Safe and Secure"
      subtitle: "You own your data. The applications can be deployed on any major cloud provider or on your priveate network."
    - title: "Our ROI Guarantee"
      subtitle: "We save our clients $M per year. If we can't at least save you what you pay us, we'll give you your money back."
    
    
  # section4_desire:
  #   title: Trusted by awesome companies like these that are saving money and improving their demand planning
  #   subtitle: Real results from our valued clients.
  #   clients:
  #   - name: Irma
  #     quote: We were able to recover $5.3M by optimizing our supply and demand planning system using Forecasting Science. They delivered a solution in 90 days. This project was a slam dunk.
  #     job: Senior VP, Exxon Mobil
  #     img: 1.png
  #   - name: John
  #     quote: We literally can't live without our new demand planning system built by Forecasting Science, LLC. These guys delivered a $3.4M improvement to operations in under 6 months.
  #     job: CEO, Tech Company
  #     img: 2.png
  #   - name: Gary
  #     quote: I finally took the plunge and boy did it pay off. We got the first version of our forecasting system in 60 days. Let's just say that the ROI was immediate.
  #     job: Executive VP, Marathon Petroleum
  #     img: 3.png
  
  section5_faq: false
  
  section6_action:
    callToActionText: Would you like to be the next success story?
    buttonText: Apply now
    buttonLink: /applynow
  
  footer:
    # Logo (from /images/logos/___)
    logo: business-science-logo.png
    navbarLogoWidth: "100px"
    navbarLogoHeight: "100px"
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # Icons are from Font Awesome
    socialmedia:
    - link: https://www.linkedin.com/
      icon: linkedin
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://github.com/lucperkins/github-fresh
      icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Consulting"
        links:
        - text: Why Data Science AI?
          link: /consulting
        # - text: Testimonials
        #   link: /testimonials
        - text: Let's do it, apply now!
          link: /applynow
      column2:
        title: "Applications"
        links:
        - text: Forecasting and Employee Turnover apps
          link: /applications
          

          
